- name: Ansible prepare
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
    - name: Install device-mapper-persistent-data
      apt:
        name: device-mapper-persistent-data
        state: latest

    - name: Install iptables
      apt:
        name: iptables
        state: latest

    - name: Install lvm2
      apt:
        name: lvm2
        state: latest

    - name: Install python3
      apt:
        name: python3
        state: latest   

    - name: Install docker pip
      pip:
        name: docker

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
      become: yes
